name: CI

on: [push]

jobs:

  build_docs:
    runs-on: self-ubuntu-20.04
    name: Build, Install, Package documentation
    if: "!contains(github.event.head_commit.message, 'docs skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Install credentials
      run: echo https://$GITHUB_OAUTH:@github.com > $HOME/.git-credentials
      env:
        GITHUB_OAUTH: ${{ secrets.DOCS_GITHUB_KEY }}
    - name: Build
      run: |
        asciidoctor README.adoc
        pdflatex tp.tex
        pdflatex tp.tex
        mkdir build
        mv README.html build/index.html
        mv tp.pdf build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
#        sudo apt install asciidoctor texlive-latex-recommended texlive-lang-french texlive-latex-extra
